// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgfvyqsJBsYFs-EPlJ25quP5yVajvMUcs',
    appId: '1:274612706912:web:4ed2644aca6fb6d2e8ed05',
    messagingSenderId: '274612706912',
    projectId: 'chatapp-6ef14',
    authDomain: 'chatapp-6ef14.firebaseapp.com',
    storageBucket: 'chatapp-6ef14.firebasestorage.app',
    measurementId: 'G-BJT1138MK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWTIP9s4YOYaZn1J5i_zdSU3VnFY74XwY',
    appId: '1:274612706912:android:e69376e4ead7d870e8ed05',
    messagingSenderId: '274612706912',
    projectId: 'chatapp-6ef14',
    storageBucket: 'chatapp-6ef14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-GEo6sDAtQfAY7J1wGSd2TAK-To3x660',
    appId: '1:274612706912:ios:12ea502761885297e8ed05',
    messagingSenderId: '274612706912',
    projectId: 'chatapp-6ef14',
    storageBucket: 'chatapp-6ef14.firebasestorage.app',
    iosBundleId: 'com.example.chatbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-GEo6sDAtQfAY7J1wGSd2TAK-To3x660',
    appId: '1:274612706912:ios:12ea502761885297e8ed05',
    messagingSenderId: '274612706912',
    projectId: 'chatapp-6ef14',
    storageBucket: 'chatapp-6ef14.firebasestorage.app',
    iosBundleId: 'com.example.chatbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgfvyqsJBsYFs-EPlJ25quP5yVajvMUcs',
    appId: '1:274612706912:web:7adf3ac4bb0eec87e8ed05',
    messagingSenderId: '274612706912',
    projectId: 'chatapp-6ef14',
    authDomain: 'chatapp-6ef14.firebaseapp.com',
    storageBucket: 'chatapp-6ef14.firebasestorage.app',
    measurementId: 'G-FCXQM23JMQ',
  );
}
